-- ── ④ Warning signs per payment, from EARLIER hours only (spec §6, Q2-Q3) ──
-- Every frame ends at 1 PRECEDING: payments in the same step are never counted.
-- Empty history: counts 0, sum/max NULL, distinct senders 0, ratio NULL (try_divide never raises).
CREATE OR REFRESH MATERIALIZED VIEW silver_transaction_features                                -- published feature table
COMMENT 'Keys plus strict-past receiver velocity features and sender history; join to silver_transactions for labels.'  -- table comment
AS SELECT                                                                                      -- keys, then features
  transaction_id,                                                                              -- key: joins to silver_transactions
  step,                                                                                        -- key: hour
  sender_account,                                                                              -- key
  receiver_account,                                                                            -- key
  COUNT(*) OVER (PARTITION BY receiver_account ORDER BY step                                   -- payments to this receiver...
    RANGE BETWEEN 1 PRECEDING AND 1 PRECEDING) AS receiver_payments_previous_hour,             -- ...in the previous hour
  COUNT(*) OVER (PARTITION BY receiver_account ORDER BY step                                   -- payments to this receiver...
    RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING) AS receiver_payments_last_24_hours,            -- ...in the 24 hours before
  SUM(amount) OVER (PARTITION BY receiver_account ORDER BY step                                -- money received...
    RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING) AS receiver_amount_last_24_hours,              -- ...in the 24 hours before
  MAX(amount) OVER (PARTITION BY receiver_account ORDER BY step                                -- largest single payment...
    RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING) AS receiver_largest_amount_last_24_hours,      -- ...in the 24 hours before
  size(collect_set(sender_account) OVER (PARTITION BY receiver_account ORDER BY step           -- different payers...
    RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING)) AS receiver_distinct_senders_last_24_hours,   -- ...in the 24 hours before
  try_divide(CAST(amount AS DOUBLE),                                                           -- this payment's size...
    try_divide(CAST(SUM(amount) OVER (PARTITION BY receiver_account ORDER BY step              -- ...relative to the receiver's...
      RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING) AS DOUBLE),                                  -- ...average incoming amount...
    CAST(COUNT(*) OVER (PARTITION BY receiver_account ORDER BY step                            -- ...over the 24 hours before
      RANGE BETWEEN 24 PRECEDING AND 1 PRECEDING) AS DOUBLE))) AS amount_vs_receiver_average_24_hours,  -- NULL when no history or zero average
  COUNT(*) OVER (PARTITION BY sender_account ORDER BY step                                     -- this sender's payments...
    RANGE BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS sender_earlier_payments              -- ...in all earlier hours (almost always 0)
FROM silver_transactions;                                                                      -- clean payments (same pipeline)
